### ISSUE TITLE
application.install is no longer added to the yaml from the website

### ISSUE THREAD

**Issue by EHLOVader** [protobox/protobox-web#11]
I was trying to figure out why my application wasn't installing and had to dig through the site.yml to find out why. There should be an application.install also in the file set to 1.

I can see some value in being able to turn off all application installs with one switch, but with it omitted nothing is installing.

example common.yml:

``` yaml
...

applications:
  install: 1
  laravel:
    - name: laravelapp
      install: 1
      path: /srv/www/web/laravel

...

```
